import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header(){
    return <div className="bg-blue-flor w-screen flex justify-center">
        <Link className="text-white font-luke-thick text-[68px] p-5 text-center" href="/">Cuentos Nocturnos</Link>
    </div>
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      <link rel="stylesheet" href="https://use.typekit.net/bys6brz.css"/>
    </head>
    <body className="bg-blue-flor">
    <Header/>
    {children}
    </body>
    </html>
  );
}
